// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	LoginTest
*/
package test

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LoginTest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Passwd           *string `protobuf:"bytes,2,req,name=passwd" json:"passwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginTest) Reset()         { *m = LoginTest{} }
func (m *LoginTest) String() string { return proto.CompactTextString(m) }
func (*LoginTest) ProtoMessage()    {}

func (m *LoginTest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LoginTest) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func init() {
}
